# Generated by Django 5.2.17 on 2026-09-18 18:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can force members to log in again'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReloginRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='aangevraagd op')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='reden')),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True, verbose_name='voldaan op')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='ingetrokken op')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ingetrokken door')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='aangevraagd door')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forcerelogin_requests', to=settings.AUTH_USER_MODEL, verbose_name='lid')),
            ],
            options={
                'verbose_name': 'herlogin-verzoek',
                'verbose_name_plural': 'herlogin-verzoeken',
                'ordering': ('-requested_at',),
                'default_permissions': (),
            },
        ),
    ]
