# Generated by Django 5.2.17 on 2026-09-18 18:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def voldane_verzoeken_afsluiten(apps, schema_editor):
    """Verzoeken van vóór de alts-fase waren klaar zodra de main inlogde.
    Zonder deze stap zouden ze met `include_alts=True` en een lege
    `alts_done_at` ineens weer als 'alts open' gelden — en het lid vast op de
    alts-pagina zetten."""
    ReloginRequest = apps.get_model("forcerelogin", "ReloginRequest")
    ReloginRequest.objects.filter(fulfilled_at__isnull=False).update(alts_done_at=F("fulfilled_at"))
    ReloginRequest.objects.filter(fulfilled_at__isnull=True).update(include_alts=False)


class Migration(migrations.Migration):

    dependencies = [
        ('forcerelogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reloginrequest',
            name='alts_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='alts klaar op'),
        ),
        migrations.AddField(
            model_name='reloginrequest',
            name='include_alts',
            field=models.BooleanField(default=True, help_text='Ook elke alt van het account moet opnieuw door EVE SSO.', verbose_name='alts ook'),
        ),
        migrations.AlterField(
            model_name='reloginrequest',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='main ingelogd op'),
        ),
        migrations.CreateModel(
            name='CharacterRelogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.PositiveBigIntegerField()),
                ('character_name', models.CharField(blank=True, default='', max_length=254)),
                ('done_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='forcerelogin.reloginrequest')),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('request', 'character_id')},
            },
        ),
        migrations.RunPython(voldane_verzoeken_afsluiten, migrations.RunPython.noop),
    ]
