# Generated by Django 5.2.17 on 2026-09-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcerelogin', '0002_alts'),
    ]

    operations = [
        migrations.AddField(
            model_name='reloginrequest',
            name='revoke_tokens',
            field=models.BooleanField(default=False, help_text='Alle ESI-tokens van het account zijn bij dit verzoek weggegooid.', verbose_name='tokens ingetrokken'),
        ),
        migrations.AddField(
            model_name='reloginrequest',
            name='tokens_revoked',
            field=models.PositiveIntegerField(default=0, help_text='Hoeveel tokens er daadwerkelijk weg zijn gegooid.', verbose_name='aantal tokens'),
        ),
    ]
